### ISSUE TITLE
TypeError when launching xtool

### ISSUE THREAD

**Issue by slauriere** [aubincleme/xtool#1]
When launching the tool after having followed the README instructions, I probably misconfigured something since I get the error below:

```
slauriere@ako:~/.xtool$ xwikit 
Traceback (most recent call last):
  File "/home/slauriere/.xtool/x.py", line 13, in <module>
    subParsers = rootParser.add_subparsers(dest='action', required=True, help='the action to perform')
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```

There might be an issue with the Python version I'm using? Here's my environment:

* Ubuntu 18.10
* Bash
* Python 2.7.15+ 

Any advice welcome :-)

**Comment by slauriere** [comment]
I gave a try with Python 3.6.7 and it seems I get the same output.

**Comment by slauriere** [comment]
I gave a new try with today's repository as follows, and I got the error below. Do you have any idea about what could cause the error?

## Installation

```
git clone git@github.com:aubincleme/xtool.git ~/.xtool
export PATH="$HOME/.xtool/xtool:$PATH"
cd ~/.xtool/xtool
virtualenv -p /usr/bin/python3 venv
source venv/bin/activate
pip install -r requirements.txt
```

## Output

```
Traceback (most recent call last):
  File "/home/slauriere/.xtool/xtool/xtool/./main.py", line 13, in <module>
    args = parse_args()
  File "/home/slauriere/.xtool/xtool/xtool/utils.py", line 38, in parse_args
    subParsers = rootParser.add_subparsers(dest='action', required=True, help='the action to perform')
  File "/usr/lib/python3.6/argparse.py", line 1716, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```

## Environment

* Python 3.6.7
* Ubuntu

**Comment by manuelleduc** [comment]
I have the exact same error with Python 3.6.9.
