### ISSUE TITLE
Make a nice error when trying to start a wrong instance

### ISSUE THREAD

**Issue by surli** [aubincleme/xtool#3]
When trying to start an instance that I didn't create yet:

```
[urli@vivat ~]$ xwiki start 10.11
Traceback (most recent call last):
  File "/home/urli/.xtool/x.py", line 52, in <module>
    im.start(args.instance_name, args.debug)
  File "/home/urli/.xtool/instances.py", line 59, in start
    subprocess.call(['{}/./{}'.format(self.getInstancePath(instanceName), startScript)])
  File "/usr/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/urli/.xtool/instances/10.11/./start_xwiki.sh': '/home/urli/.xtool/instances/10.11/./start_xwiki.sh'
```

Would be better to have a nice message :)

**Comment by aubincleme** [comment]
@surli 763f88e should do the work :)
