### ISSUE TITLE
Xtool does not work anymore after upgrade to Ubuntu 22.04

### ISSUE THREAD

**Issue by lucaa** [aubincleme/xtool#37]
The error is something like this: 

```
$x -h
Traceback (most recent call last):
  File "<redacted>/xtool/xtool/./main.py", line 5, in <module>
    from configuration import ConfigManager
  File "<redacted>/xtool/xtool/configuration.py", line 5, in <module>
    from watchdog.observers import Observer
ModuleNotFoundError: No module named 'watchdog'

```

**Comment by lucaa** [comment]
apparently I'm missing rights to triage this ticket, it's a bug (should have the bug label).

**Comment by lucaa** [comment]
I fixed the issue by re-creating the venv , as follows:
* I copied the ```venv``` folder from ```<checkout>/xtool``` into a backup one
* I deleted the venv folder
* I re-ran the steps from **point 3** here https://github.com/aubincleme/xtool#installation 
* success!
